### PR TITLE
Navigation measurement accessors.

### PR DESCRIPTION
**Pull request by mookerji**
0. Expose attributes of the navigation measurement.
1. tot -> tow in navigation measurement attributes.

/cc @fnoble @imh

### CODE REVIEW

**Comment by mookerji** [comment]
lgti(an)

**Comment by fnoble** [comment]
TOT was not a typo here, stands for time of transmit. Its pretty important to change this back.

**Comment by fnoble** [comment]
Also should consider exposing this as a `GpsTime`, this would allow us to pass it in again to C functions expecting a `gps_time_t`

**Comment by mookerji** [comment]
@fnoble got it.

**Pull request merged**
